"""Scaffold a new LAOS project under projects/<name>/.

Usage:
    uv run python scripts/bootstrap_project.py <name> --workflow <workflow>
    uv run python scripts/bootstrap_project.py <name>              # ad-hoc
    uv run python scripts/bootstrap_project.py --list-workflows

Validates:
- name is unique (projects/<name> does not exist)
- workflow exists under workflows/ and is valid YAML
- every need in the workflow is routable via registry/needs-to-capabilities.yaml
- creates artifacts/<stage>/ directories for each workflow stage
- writes a starter project.yaml
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
PROJECTS = ROOT / "projects"
WORKFLOWS = ROOT / "workflows"
REGISTRY = ROOT / "registry"


def load_yaml(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def list_workflows() -> list[str]:
    return sorted(p.stem for p in WORKFLOWS.glob("*.yaml"))


def validate_needs(needs: list[str], routing: dict) -> list[str]:
    """Return list of needs that have no routing rule."""
    return [n for n in needs if n not in routing]


def scaffold(name: str, workflow: str | None, description: str | None) -> int:
    if not name.replace("-", "").replace("_", "").isalnum():
        print(f"[err] project name must be alphanumeric (got: {name!r})")
        return 2

    target = PROJECTS / name
    if target.exists():
        print(f"[err] {target} already exists")
        return 2

    needs: list[str] = []
    deliverables: list[str] = []
    inputs: list[str] = []
    stages: list[str] = []
    workflow_name: str | None = None

    if workflow:
        wf_path = WORKFLOWS / f"{workflow}.yaml"
        if not wf_path.exists():
            print(f"[err] workflow not found: {wf_path}")
            print(f"      available: {', '.join(list_workflows())}")
            return 2
        wf = load_yaml(wf_path)
        workflow_name = wf.get("name", workflow)
        needs = list(wf.get("needs") or [])
        deliverables = list(wf.get("deliverables") or [])
        inputs = list(wf.get("inputs") or [])
        stages = list(wf.get("stages") or [])

    routing_doc = load_yaml(REGISTRY / "needs-to-capabilities.yaml")
    routing = routing_doc if isinstance(routing_doc, dict) and "routing" not in routing_doc else routing_doc.get("routing", {})
    unrouted = validate_needs(needs, routing)
    if unrouted:
        print(f"[err] workflow has needs with no routing rule: {unrouted}")
        print(f"      add them to {REGISTRY / 'needs-to-capabilities.yaml'}")
        return 2

    PROJECTS.mkdir(parents=True, exist_ok=True)
    target.mkdir(parents=True)

    for stage in stages:
        stage_id = stage["id"] if isinstance(stage, dict) else stage
        (target / "artifacts" / stage_id).mkdir(parents=True)
    if "review" not in [s["id"] if isinstance(s, dict) else s for s in stages]:
        (target / "artifacts" / "review").mkdir(parents=True)

    project_yaml = {
        "name": name,
        "description": description or f"<one-line description for {name}>",
        "workflow": workflow_name,
        "external_delivery": False,
        "needs": needs,
        "deliverables": deliverables,
        "inputs": inputs,
        "input_values": {},  # filled in by the user
    }
    with (target / "project.yaml").open("w", encoding="utf-8") as fh:
        yaml.safe_dump(project_yaml, fh, sort_keys=False, allow_unicode=True)

    readme = (
        f"# {name}\n\n"
        f"> Generated by LAOS bootstrap. Edit `project.yaml` to add real "
        f"description and inputs.\n\n"
        f"## Workflow\n\n"
        f"Workflow: `{workflow_name or 'ad-hoc'}`\n\n"
        f"## Needs\n\n"
        + "\n".join(f"- {n}" for n in needs)
        + "\n\n## Artifacts\n\nArtifacts live in `artifacts/<stage>/`.\n"
    )
    (target / "README.md").write_text(readme, encoding="utf-8")

    print(f"[ok] scaffolded {target}")
    print(f"      workflow: {workflow_name or '(ad-hoc)'}")
    print(f"      needs:    {', '.join(needs) or '(none)'}")
    stage_ids = [s['id'] if isinstance(s, dict) else s for s in stages]
    print(f"      stages:   {', '.join(stage_ids) or '(none)'}")
    print()
    print("next: ask the orchestrator to execute the first stage.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Scaffold a new LAOS project")
    parser.add_argument("name", nargs="?", help="project name (folder under projects/)")
    parser.add_argument("--workflow", help="workflow name (filename stem under workflows/)")
    parser.add_argument("--description", help="one-line description for project.yaml")
    parser.add_argument(
        "--list-workflows",
        action="store_true",
        help="list available workflows and exit",
    )
    args = parser.parse_args()

    if args.list_workflows:
        for wf in list_workflows():
            print(wf)
        return 0

    if not args.name:
        parser.print_help()
        return 2

    return scaffold(args.name, args.workflow, args.description)


if __name__ == "__main__":
    sys.exit(main())
